import { createFileRoute, Link } from "@tanstack/react-router";
import { PublicLayout } from "@/components/layout/PublicLayout";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — ThreadCounty" },
      { name: "description", content: "ThreadCounty terms of service — rules governing your use of the platform." },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <PublicLayout>
      <section className="mx-auto max-w-3xl px-6 py-20">
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-10">
          <ArrowLeft className="size-4" /> Back to home
        </Link>

        <div className="tag mb-4">Legal</div>
        <h1 className="text-4xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="mt-3 font-mono text-xs text-muted-foreground uppercase tracking-widest">Effective: 1 June 2026</p>

        <div className="mt-12 space-y-10 text-sm leading-relaxed text-muted-foreground">
          <Section title="1. Acceptance of terms">
            By accessing or using ThreadCounty ("the Service"), you agree to be bound by these Terms of Service.
            If you do not agree, do not use the Service. These terms apply to all users including free and paid plan subscribers.
          </Section>

          <Section title="2. Description of service">
            ThreadCounty provides AI-powered textile fabric analysis including thread density measurement, weave
            identification, and quality control reporting. The Service is provided via a web interface and API.
          </Section>

          <Section title="3. Account registration">
            You must provide a valid email address and create a password to use the Service. You are responsible
            for maintaining the confidentiality of your credentials. You must be at least 16 years old to register.
            One person may not maintain more than one free account.
          </Section>

          <Section title="4. Acceptable use">
            You agree not to:
            <ul className="mt-3 space-y-2 list-disc list-inside">
              <li>Upload images containing illegal, harmful, or offensive content.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the AI analysis API.</li>
              <li>Resell or redistribute analysis reports generated by the Service without permission.</li>
              <li>Use automated tools to create accounts or submit analyses in bulk beyond your plan limits.</li>
              <li>Attempt to gain unauthorized access to other users' data or the underlying infrastructure.</li>
            </ul>
          </Section>

          <Section title="5. Subscription and billing">
            Paid plans are billed monthly. You may cancel at any time; access continues until the end of the
            current billing period. Refunds are provided at our discretion for billing errors. Prices may change
            with 30 days' notice to active subscribers.
          </Section>

          <Section title="6. Intellectual property">
            ThreadCounty retains all rights to the platform, AI models, and interface. Your fabric images remain
            your property. You grant ThreadCounty a limited license to process your images solely to provide
            analysis results. We may use anonymised, aggregated data to improve our models.
          </Section>

          <Section title="7. Accuracy disclaimer">
            Analysis results are generated by computer vision AI and are provided for informational purposes.
            While we target 99.8% accuracy on standard woven fabrics, results should be verified against physical
            laboratory methods for critical quality decisions. ThreadCounty is not liable for production or
            commercial decisions made solely on the basis of automated analysis.
          </Section>

          <Section title="8. Limitation of liability">
            To the maximum extent permitted by law, ThreadCounty shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages arising from your use of the Service. Our total liability
            shall not exceed the amounts paid by you in the 3 months preceding the claim.
          </Section>

          <Section title="9. Termination">
            We may suspend or terminate accounts that violate these terms. You may close your account at any time.
            Upon termination, your data will be retained for 30 days before permanent deletion, unless you request
            immediate deletion.
          </Section>

          <Section title="10. Governing law">
            These terms are governed by the laws of India. Disputes shall be subject to the exclusive jurisdiction
            of courts in New Delhi, India.
          </Section>

          <Section title="11. Changes to terms">
            We may update these terms and will notify users via email for material changes. Continued use after
            changes constitutes acceptance of the updated terms.
          </Section>

          <Section title="12. Contact">
            For questions about these terms, contact{" "}
            <a href="mailto:legal@threadcounty.com" className="text-brand hover:underline">
              legal@threadcounty.com
            </a>.
          </Section>
        </div>
      </section>
    </PublicLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-base font-semibold text-foreground">{title}</h2>
      <div className="mt-2">{children}</div>
    </div>
  );
}
